services:
  apiforfirstangular:
    image: apiforfirstangular
    build:
      context: .
      dockerfile: ApiForFirstAngular/Dockerfile
    ports:
        - "7137:8080"
    container_name: Api
  angular:
    image: frontimage
    build:
        context: .
        dockerfile: FrontEnd_Angular/Dockerfile
    ports:
        - "4200:4200"
    volumes:
          - ./FrontEnd_Angular:/app
          - /app/node_modules
    container_name: Front
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=admin
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"